---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: psql-init-instance-1604
    image: geerlingguy/docker-ubuntu1604-ansible
    pre_build_image: true
  - name: psql-init-instance-2004
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
